apiVersion: v1
kind: ConfigMap
metadata:
  name: orderhub-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5433/orderhub
  SPRING_DATASOURCE_USERNAME: orderhub
  SPRING_DATA_REDIS_HOST: host.docker.internal
  SPRING_DATA_REDIS_PORT: "6379"